from pydantic import BaseModel, Field


class ResearchRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=5,
        description="Research question"
    )


class ResearchPlan(BaseModel):
    queries: list[str] = Field(
        ...,
        min_length=3,
        max_length=5,
        description="Search queries generated by the planner"
    )